import { createSlice } from '@reduxjs/toolkit'

export interface NavbarState {
  isExpanded: boolean
  activeTab?: string
  videos: []
}

const initialState: NavbarState = {
  isExpanded: false,
  activeTab: '',
  videos: []
}

const navbarSlice = createSlice({
  name: 'navbar',
  initialState,
  reducers: {
    extended(state: NavbarState, action: { payload: { isExpanded: boolean, activeTab: string } }) {
      state.isExpanded = action.payload.isExpanded
      state.activeTab = action.payload.activeTab
    },
    setVideos(state: NavbarState, action: unknown) {
      state.videos = action.payload.videos
    }
  },
})

// Export the actions generated by the Slice
export const { extended, setVideos } = navbarSlice.actions

// Export the reducer
export default navbarSlice.reducer
