import { createSlice } from '@reduxjs/toolkit'

export interface NavbarState {
  isExpanded: boolean
  activeTab?: string
}

const initialState: NavbarState = {
  isExpanded: false,
  activeTab: '',
}

const navbarSlice = createSlice({
  name: 'navbar',
  initialState,
  reducers: {
    extended(state: NavbarState, action: { payload: boolean }) {
      state.isExpanded = action.payload
    },
    activeTabF(state: NavbarState, action: { payload: string }) {
      state.activeTab = action.payload
    },
    // You can add other actions as needed
  },
})

// Export the actions generated by the Slice
export const { extended, activeTabF } = navbarSlice.actions

// Export the reducer
export default navbarSlice.reducer
