import { createSlice } from '@reduxjs/toolkit'

export interface IResize {
  x: string
  y: string
  w: string
  h: string
}

const initialState: IResize = {
  x: 'x',
  y: 'yyy',
  w: 'www',
  h: 'hhh',
}

interface IPayload {
  payload: { [key: string]: string }
}

const resizeSlice = createSlice({
  name: 'resize',
  initialState,
  reducers: {
    setCoordX(state: IResize, action: IPayload) {
      state.x = action.payload.x
    },
    setCoordY(state: IResize, action: IPayload) {
      state.y = action.payload.y
    },
    setSizeW(state: IResize, action: IPayload) {
      state.w = action.payload.w
    },
    setSizeH(state: IResize, action: IPayload) {
      state.h = action.payload.h
    },
  },
})

// Export the actions generated by the Slice
export const {
  setCoordX,
  setCoordY,
  setSizeW,
  setSizeH,
} = resizeSlice.actions

// Export the reducer
export default resizeSlice.reducer
