export const shapes = [
  { id: 1, src: "/src/assets/shapes/arrow.svg" },
  { id: 2, src: "/src/assets/shapes/circle.svg"},
  { id: 3, src: "/src/assets/shapes/heart.svg"},
  { id: 4, src: "/src/assets/shapes/hexagon.svg"},
  { id: 5, src: "/src/assets/shapes/polygon.svg" },
  { id: 6, src: "/src/assets/shapes/rectangle.svg" },
  { id: 7, src: "/src/assets/shapes/star.svg" },
  { id: 8, src: "/src/assets/shapes/triangle.svg" },
]

export const img = [
  { id: 1, src: "/src/assets/images/image1.avif" },
  { id: 2, src: "/src/assets/images/image2.avif"},
  { id: 3, src: "/src/assets/images/image3.avif"},
  { id: 4, src: "/src/assets/images/image4.avif"},
  { id: 5, src: "/src/assets/images/image5.avif" },
  { id: 6, src: "/src/assets/images/image6.avif" },
  { id: 7, src: "/src/assets/images/image7.avif" },
]

export const emojis = [
  { id: 1, src: "/src/assets/emojis/bomb-emoji.png" },
  { id: 2, src: "/src/assets/emojis/cat-face-emoji.png"},
  { id: 3, src: "/src/assets/emojis/clap-emoji.png"},
  { id: 4, src: "/src/assets/emojis/crying-emoji.png"},
  { id: 5, src: "/src/assets/emojis/clock-emoji.png" },
  { id: 6, src: "/src/assets/emojis/construction-emoji.png" },
  { id: 7, src: "/src/assets/emojis/dog-face-emoji.png" },
  { id: 8, src: "/src/assets/emojis/eyes-emoji.png" },
  { id: 9, src: "/src/assets/emojis/fire-emoji.png" },
  { id: 10, src: "/src/assets/emojis/gem-emoji.png" },
  { id: 11, src: "/src/assets/emojis/ghost-emoji.png" },
  { id: 12, src: "/src/assets/emojis/gift-emoji.png" },
  { id: 13, src: "/src/assets/emojis/graph-emoji.png" },
  { id: 14, src: "/src/assets/emojis/heart-eyes-emoji.png" },
  { id: 15, src: "/src/assets/emojis/hundred-100-points-emoji.png" },
  { id: 16, src: "/src/assets/emojis/laughing-emoji.png" },
  { id: 17, src: "/src/assets/emojis/mindblown-emoji.png" },
  { id: 18, src: "/src/assets/emojis/money-emoji.png" },
  { id: 19, src: "/src/assets/emojis/moon-emoji.png" },
  { id: 20, src: "/src/assets/emojis/nail-polish-emoji.png" },
  { id: 21, src: "/src/assets/emojis/party-popper-emoji.png" },
  { id: 22, src: "/src/assets/emojis/pencil-emoji.png" },
  { id: 23, src: "/src/assets/emojis/pizza-emoji.png" },
  { id: 24, src: "/src/assets/emojis/plane-emoji.png" },
  { id: 25, src: "/src/assets/emojis/pleading-face-emoji.png" },
  { id: 26, src: "/src/assets/emojis/point-emoji.png" },
  { id: 27, src: "/src/assets/emojis/praying-hands-emoji.png" },
  { id: 28, src: "/src/assets/emojis/raising-hands-emoji.png" },
  { id: 29, src: "/src/assets/emojis/rose-emoji.png" },
  { id: 30, src: "/src/assets/emojis/skull-emoji.png" },
  { id: 31, src: "/src/assets/emojis/smiling-emoji.png" },
  { id: 32, src: "/src/assets/emojis/sparkles-emoji.png" },
  { id: 33, src: "/src/assets/emojis/star-emoji.png" },
  { id: 34, src: "/src/assets/emojis/sun-emoji.png" },
  { id: 35, src: "/src/assets/emojis/sunglasses-cool-emoji.png" },
  { id: 36, src: "/src/assets/emojis/surprised-emoji.png" },
  { id: 37, src: "/src/assets/emojis/target-emoji.png" },
  { id: 38, src: "/src/assets/emojis/thinking-face-emoji.png" },
  { id: 39, src: "/src/assets/emojis/thought-balloon-emoji.png" },
  { id: 40, src: "/src/assets/emojis/thumbs-up-emoji.png" },
  { id: 41, src: "/src/assets/emojis/tongue-emoji.png" },
  { id: 42, src: "/src/assets/emojis/trophy-emoji.png" },
  { id: 43, src: "/src/assets/emojis/tulip-emoji.png" },
  { id: 44, src: "/src/assets/emojis/thought-balloon-emoji.png" },
  { id: 45, src: "/src/assets/emojis/wave-emoji.png" },
  { id: 46, src: "/src/assets/emojis/winking-face-emoji.png" },
  { id: 47, src: "/src/assets/emojis/wip-emoji.png" },
]